on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        with:
          #token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN
          target-branch: main
          config-file: .github/workflows/.release-please-config.json
          manifest-file: .github/workflows/.release-please-manifest.json
